name: bill_scanner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Image & Scanner
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0

  # Network
  http: ^1.2.2

  # Storage & Files
  path_provider: ^2.1.4

  # UI & Design
  google_fonts: ^6.2.1
  lottie: ^3.1.0

  # Charts
  fl_chart: ^0.68.0

  # Date & Format
  intl: ^0.19.0

  # Firebase (Aligned versions)
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.0

  # Video (optional if used)
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/bill_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/bill_logo.png